#!/bin/bash

# ci_post_clone.sh - Inject secrets from Xcode Cloud env vars into a generated xcconfig

set -e  # Exit on error

echo "Generating Secrets.xcconfig from environment variables..."

cat > Secrets.xcconfig << EOL
// Auto-generated by ci_post_clone.sh - DO NOT EDIT
REVENUECAT_API_KEY = $REVENUECAT_API_KEY
GEMINI_API_KEY = $GEMINI_API_KEY
EOL

echo "Generated Secrets.xcconfig:"
cat Secrets.xcconfig
